/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CreateOrderPackageType Требования к упаковке:  * `WHITELABEL` — коробка.  * `BRAND` — [брендированная упаковка](*brand-package) магазина.  Если не передать `packageType`, заказ приедет в коробке или без упаковки.
type CreateOrderPackageType string

// List of CreateOrderPackageType
const (
	CREATEORDERPACKAGETYPE_WHITELABEL CreateOrderPackageType = "WHITELABEL"
	CREATEORDERPACKAGETYPE_BRAND      CreateOrderPackageType = "BRAND"
)

// All allowed values of CreateOrderPackageType enum
var AllowedCreateOrderPackageTypeEnumValues = []CreateOrderPackageType{
	"WHITELABEL",
	"BRAND",
}

func (v *CreateOrderPackageType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CreateOrderPackageType(value)
	for _, existing := range AllowedCreateOrderPackageTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CreateOrderPackageType", value)
}

// NewCreateOrderPackageTypeFromValue returns a pointer to a valid CreateOrderPackageType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCreateOrderPackageTypeFromValue(v string) (*CreateOrderPackageType, error) {
	ev := CreateOrderPackageType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CreateOrderPackageType: valid values are %v", v, AllowedCreateOrderPackageTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CreateOrderPackageType) IsValid() bool {
	for _, existing := range AllowedCreateOrderPackageTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CreateOrderPackageType value
func (v CreateOrderPackageType) Ptr() *CreateOrderPackageType {
	return &v
}

type NullableCreateOrderPackageType struct {
	value *CreateOrderPackageType
	isSet bool
}

func (v NullableCreateOrderPackageType) Get() *CreateOrderPackageType {
	return v.value
}

func (v *NullableCreateOrderPackageType) Set(val *CreateOrderPackageType) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderPackageType) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderPackageType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderPackageType(val *CreateOrderPackageType) *NullableCreateOrderPackageType {
	return &NullableCreateOrderPackageType{value: val, isSet: true}
}

func (v NullableCreateOrderPackageType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderPackageType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
