/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AnswerListDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnswerListDTO{}

// AnswerListDTO Ответы на вопрос.
type AnswerListDTO struct {
	// Список ответов.
	Answers []AnswerDTO                        `json:"answers"`
	Paging  *PackagingForwardScrollingPagerDTO `json:"paging,omitempty"`
}

type _AnswerListDTO AnswerListDTO

// NewAnswerListDTO instantiates a new AnswerListDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnswerListDTO(answers []AnswerDTO) *AnswerListDTO {
	this := AnswerListDTO{}
	this.Answers = answers
	return &this
}

// NewAnswerListDTOWithDefaults instantiates a new AnswerListDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnswerListDTOWithDefaults() *AnswerListDTO {
	this := AnswerListDTO{}
	return &this
}

// GetAnswers returns the Answers field value
func (o *AnswerListDTO) GetAnswers() []AnswerDTO {
	if o == nil {
		var ret []AnswerDTO
		return ret
	}

	return o.Answers
}

// GetAnswersOk returns a tuple with the Answers field value
// and a boolean to check if the value has been set.
func (o *AnswerListDTO) GetAnswersOk() ([]AnswerDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.Answers, true
}

// SetAnswers sets field value
func (o *AnswerListDTO) SetAnswers(v []AnswerDTO) {
	o.Answers = v
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *AnswerListDTO) GetPaging() PackagingForwardScrollingPagerDTO {
	if o == nil || IsNil(o.Paging) {
		var ret PackagingForwardScrollingPagerDTO
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnswerListDTO) GetPagingOk() (*PackagingForwardScrollingPagerDTO, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *AnswerListDTO) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given PackagingForwardScrollingPagerDTO and assigns it to the Paging field.
func (o *AnswerListDTO) SetPaging(v PackagingForwardScrollingPagerDTO) {
	o.Paging = &v
}

func (o AnswerListDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnswerListDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answers"] = o.Answers
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	return toSerialize, nil
}

func (o *AnswerListDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnswerListDTO := _AnswerListDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnswerListDTO)

	if err != nil {
		return err
	}

	*o = AnswerListDTO(varAnswerListDTO)

	return err
}

type NullableAnswerListDTO struct {
	value *AnswerListDTO
	isSet bool
}

func (v NullableAnswerListDTO) Get() *AnswerListDTO {
	return v.value
}

func (v *NullableAnswerListDTO) Set(val *AnswerListDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableAnswerListDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableAnswerListDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnswerListDTO(val *AnswerListDTO) *NullableAnswerListDTO {
	return &NullableAnswerListDTO{value: val, isSet: true}
}

func (v NullableAnswerListDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnswerListDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
