/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VotesDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VotesDTO{}

// VotesDTO Количество лайков и дизлайков на вопросе, ответе или комментарии.
type VotesDTO struct {
	// Количество лайков.
	Likes int64 `json:"likes"`
	// Количество дизлайков.
	Dislikes int64 `json:"dislikes"`
}

type _VotesDTO VotesDTO

// NewVotesDTO instantiates a new VotesDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVotesDTO(likes int64, dislikes int64) *VotesDTO {
	this := VotesDTO{}
	this.Likes = likes
	this.Dislikes = dislikes
	return &this
}

// NewVotesDTOWithDefaults instantiates a new VotesDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVotesDTOWithDefaults() *VotesDTO {
	this := VotesDTO{}
	return &this
}

// GetLikes returns the Likes field value
func (o *VotesDTO) GetLikes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Likes
}

// GetLikesOk returns a tuple with the Likes field value
// and a boolean to check if the value has been set.
func (o *VotesDTO) GetLikesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Likes, true
}

// SetLikes sets field value
func (o *VotesDTO) SetLikes(v int64) {
	o.Likes = v
}

// GetDislikes returns the Dislikes field value
func (o *VotesDTO) GetDislikes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Dislikes
}

// GetDislikesOk returns a tuple with the Dislikes field value
// and a boolean to check if the value has been set.
func (o *VotesDTO) GetDislikesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dislikes, true
}

// SetDislikes sets field value
func (o *VotesDTO) SetDislikes(v int64) {
	o.Dislikes = v
}

func (o VotesDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VotesDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["likes"] = o.Likes
	toSerialize["dislikes"] = o.Dislikes
	return toSerialize, nil
}

func (o *VotesDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"likes",
		"dislikes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVotesDTO := _VotesDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVotesDTO)

	if err != nil {
		return err
	}

	*o = VotesDTO(varVotesDTO)

	return err
}

type NullableVotesDTO struct {
	value *VotesDTO
	isSet bool
}

func (v NullableVotesDTO) Get() *VotesDTO {
	return v.value
}

func (v *NullableVotesDTO) Set(val *VotesDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableVotesDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableVotesDTO) Unset() {
	var zero *VotesDTO
	v.value = zero
	v.isSet = false
}

func NewNullableVotesDTO(val *VotesDTO) *NullableVotesDTO {
	return &NullableVotesDTO{value: val, isSet: true}
}

func (v NullableVotesDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVotesDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
