/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OperationType Тип операции:  * `ORDER_RECIPIENT_UPDATE` — изменение данных получателя.  * `ORDER_DELIVERY_INTERVAL_UPDATE` — изменение интервала дат доставки.  * `ORDER_STATUS_UPDATE` — обновление статуса заказа для его отмены.  * `RETURN_CANCELLATION` — отмена возврата.
type OperationType string

// List of OperationType
const (
	OPERATIONTYPE_ORDER_RECIPIENT_UPDATE         OperationType = "ORDER_RECIPIENT_UPDATE"
	OPERATIONTYPE_ORDER_DELIVERY_INTERVAL_UPDATE OperationType = "ORDER_DELIVERY_INTERVAL_UPDATE"
	OPERATIONTYPE_ORDER_STATUS_UPDATE            OperationType = "ORDER_STATUS_UPDATE"
	OPERATIONTYPE_RETURN_CANCELLATION            OperationType = "RETURN_CANCELLATION"
)

// All allowed values of OperationType enum
var AllowedOperationTypeEnumValues = []OperationType{
	"ORDER_RECIPIENT_UPDATE",
	"ORDER_DELIVERY_INTERVAL_UPDATE",
	"ORDER_STATUS_UPDATE",
	"RETURN_CANCELLATION",
}

func (v *OperationType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OperationType(value)
	for _, existing := range AllowedOperationTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OperationType", value)
}

// NewOperationTypeFromValue returns a pointer to a valid OperationType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOperationTypeFromValue(v string) (*OperationType, error) {
	ev := OperationType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OperationType: valid values are %v", v, AllowedOperationTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OperationType) IsValid() bool {
	for _, existing := range AllowedOperationTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OperationType value
func (v OperationType) Ptr() *OperationType {
	return &v
}

type NullableOperationType struct {
	value *OperationType
	isSet bool
}

func (v NullableOperationType) Get() *OperationType {
	return v.value
}

func (v *NullableOperationType) Set(val *OperationType) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationType) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationType(val *OperationType) *NullableOperationType {
	return &NullableOperationType{value: val, isSet: true}
}

func (v NullableOperationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
