/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiLimitErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiLimitErrorResponse{}

// ApiLimitErrorResponse Превышено ограничение на доступ к ресурсу.
type ApiLimitErrorResponse struct {
	Status *ApiResponseStatusType `json:"status,omitempty"`
	// Список ошибок.
	Errors []ApiErrorDTO `json:"errors,omitempty"`
}

// NewApiLimitErrorResponse instantiates a new ApiLimitErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiLimitErrorResponse() *ApiLimitErrorResponse {
	this := ApiLimitErrorResponse{}
	return &this
}

// NewApiLimitErrorResponseWithDefaults instantiates a new ApiLimitErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiLimitErrorResponseWithDefaults() *ApiLimitErrorResponse {
	this := ApiLimitErrorResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApiLimitErrorResponse) GetStatus() ApiResponseStatusType {
	if o == nil || IsNil(o.Status) {
		var ret ApiResponseStatusType
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiLimitErrorResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApiLimitErrorResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ApiResponseStatusType and assigns it to the Status field.
func (o *ApiLimitErrorResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiLimitErrorResponse) GetErrors() []ApiErrorDTO {
	if o == nil {
		var ret []ApiErrorDTO
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiLimitErrorResponse) GetErrorsOk() ([]ApiErrorDTO, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ApiLimitErrorResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ApiErrorDTO and assigns it to the Errors field.
func (o *ApiLimitErrorResponse) SetErrors(v []ApiErrorDTO) {
	o.Errors = v
}

func (o ApiLimitErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiLimitErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableApiLimitErrorResponse struct {
	value *ApiLimitErrorResponse
	isSet bool
}

func (v NullableApiLimitErrorResponse) Get() *ApiLimitErrorResponse {
	return v.value
}

func (v *NullableApiLimitErrorResponse) Set(val *ApiLimitErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiLimitErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiLimitErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiLimitErrorResponse(val *ApiLimitErrorResponse) *NullableApiLimitErrorResponse {
	return &NullableApiLimitErrorResponse{value: val, isSet: true}
}

func (v NullableApiLimitErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiLimitErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


