/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetCampaignOffersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCampaignOffersRequest{}

// GetCampaignOffersRequest Фильтрации товаров  В запросе можно указать либо фильтр offerIds, либо любые другие фильтры товаров. Совместное использование фильтра offerIds с другими фильтрациями приведет к ошибке.
type GetCampaignOffersRequest struct {
	// Идентификаторы товаров, информация о которых нужна.  {% note warning \"Такой список возвращается только целиком\" %}  Не используйте это поле одновременно с фильтрами по статусам карточек, категориям, брендам или тегам. Если вы хотите воспользоваться фильтрами, оставьте поле пустым.  Если вы запрашиваете информацию по конкретным SKU, не заполняйте:  * `page_token` * `limit`  {% endnote %}
	OfferIds []string `json:"offerIds,omitempty"`
	// Фильтр по статусам товаров.
	Statuses []OfferCampaignStatusType `json:"statuses,omitempty"`
	// Фильтр по категориям на Маркете.
	CategoryIds []int32 `json:"categoryIds,omitempty"`
	// Фильтр по брендам.
	VendorNames []string `json:"vendorNames,omitempty"`
	// Фильтр по тегам.
	Tags []string `json:"tags,omitempty"`
}

// NewGetCampaignOffersRequest instantiates a new GetCampaignOffersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCampaignOffersRequest() *GetCampaignOffersRequest {
	this := GetCampaignOffersRequest{}
	return &this
}

// NewGetCampaignOffersRequestWithDefaults instantiates a new GetCampaignOffersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCampaignOffersRequestWithDefaults() *GetCampaignOffersRequest {
	this := GetCampaignOffersRequest{}
	return &this
}

// GetOfferIds returns the OfferIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCampaignOffersRequest) GetOfferIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.OfferIds
}

// GetOfferIdsOk returns a tuple with the OfferIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCampaignOffersRequest) GetOfferIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.OfferIds) {
		return nil, false
	}
	return o.OfferIds, true
}

// HasOfferIds returns a boolean if a field has been set.
func (o *GetCampaignOffersRequest) HasOfferIds() bool {
	if o != nil && !IsNil(o.OfferIds) {
		return true
	}

	return false
}

// SetOfferIds gets a reference to the given []string and assigns it to the OfferIds field.
func (o *GetCampaignOffersRequest) SetOfferIds(v []string) {
	o.OfferIds = v
}

// GetStatuses returns the Statuses field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCampaignOffersRequest) GetStatuses() []OfferCampaignStatusType {
	if o == nil {
		var ret []OfferCampaignStatusType
		return ret
	}
	return o.Statuses
}

// GetStatusesOk returns a tuple with the Statuses field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCampaignOffersRequest) GetStatusesOk() ([]OfferCampaignStatusType, bool) {
	if o == nil || IsNil(o.Statuses) {
		return nil, false
	}
	return o.Statuses, true
}

// HasStatuses returns a boolean if a field has been set.
func (o *GetCampaignOffersRequest) HasStatuses() bool {
	if o != nil && !IsNil(o.Statuses) {
		return true
	}

	return false
}

// SetStatuses gets a reference to the given []OfferCampaignStatusType and assigns it to the Statuses field.
func (o *GetCampaignOffersRequest) SetStatuses(v []OfferCampaignStatusType) {
	o.Statuses = v
}

// GetCategoryIds returns the CategoryIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCampaignOffersRequest) GetCategoryIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.CategoryIds
}

// GetCategoryIdsOk returns a tuple with the CategoryIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCampaignOffersRequest) GetCategoryIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.CategoryIds) {
		return nil, false
	}
	return o.CategoryIds, true
}

// HasCategoryIds returns a boolean if a field has been set.
func (o *GetCampaignOffersRequest) HasCategoryIds() bool {
	if o != nil && !IsNil(o.CategoryIds) {
		return true
	}

	return false
}

// SetCategoryIds gets a reference to the given []int32 and assigns it to the CategoryIds field.
func (o *GetCampaignOffersRequest) SetCategoryIds(v []int32) {
	o.CategoryIds = v
}

// GetVendorNames returns the VendorNames field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCampaignOffersRequest) GetVendorNames() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.VendorNames
}

// GetVendorNamesOk returns a tuple with the VendorNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCampaignOffersRequest) GetVendorNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.VendorNames) {
		return nil, false
	}
	return o.VendorNames, true
}

// HasVendorNames returns a boolean if a field has been set.
func (o *GetCampaignOffersRequest) HasVendorNames() bool {
	if o != nil && !IsNil(o.VendorNames) {
		return true
	}

	return false
}

// SetVendorNames gets a reference to the given []string and assigns it to the VendorNames field.
func (o *GetCampaignOffersRequest) SetVendorNames(v []string) {
	o.VendorNames = v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCampaignOffersRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCampaignOffersRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetCampaignOffersRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *GetCampaignOffersRequest) SetTags(v []string) {
	o.Tags = v
}

func (o GetCampaignOffersRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCampaignOffersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OfferIds != nil {
		toSerialize["offerIds"] = o.OfferIds
	}
	if o.Statuses != nil {
		toSerialize["statuses"] = o.Statuses
	}
	if o.CategoryIds != nil {
		toSerialize["categoryIds"] = o.CategoryIds
	}
	if o.VendorNames != nil {
		toSerialize["vendorNames"] = o.VendorNames
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableGetCampaignOffersRequest struct {
	value *GetCampaignOffersRequest
	isSet bool
}

func (v NullableGetCampaignOffersRequest) Get() *GetCampaignOffersRequest {
	return v.value
}

func (v *NullableGetCampaignOffersRequest) Set(val *GetCampaignOffersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCampaignOffersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCampaignOffersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCampaignOffersRequest(val *GetCampaignOffersRequest) *NullableGetCampaignOffersRequest {
	return &NullableGetCampaignOffersRequest{value: val, isSet: true}
}

func (v NullableGetCampaignOffersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCampaignOffersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
