/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetCategoryContentParametersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCategoryContentParametersResponse{}

// GetCategoryContentParametersResponse Ответ со списком характеристик для категории и их допустимыми значениями.
type GetCategoryContentParametersResponse struct {
	Status ApiResponseStatusType         `json:"status"`
	Result *CategoryContentParametersDTO `json:"result,omitempty"`
}

type _GetCategoryContentParametersResponse GetCategoryContentParametersResponse

// NewGetCategoryContentParametersResponse instantiates a new GetCategoryContentParametersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCategoryContentParametersResponse(status ApiResponseStatusType) *GetCategoryContentParametersResponse {
	this := GetCategoryContentParametersResponse{}
	this.Status = status
	return &this
}

// NewGetCategoryContentParametersResponseWithDefaults instantiates a new GetCategoryContentParametersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCategoryContentParametersResponseWithDefaults() *GetCategoryContentParametersResponse {
	this := GetCategoryContentParametersResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetCategoryContentParametersResponse) GetStatus() ApiResponseStatusType {
	if o == nil {
		var ret ApiResponseStatusType
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetCategoryContentParametersResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetCategoryContentParametersResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetCategoryContentParametersResponse) GetResult() CategoryContentParametersDTO {
	if o == nil || IsNil(o.Result) {
		var ret CategoryContentParametersDTO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCategoryContentParametersResponse) GetResultOk() (*CategoryContentParametersDTO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetCategoryContentParametersResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given CategoryContentParametersDTO and assigns it to the Result field.
func (o *GetCategoryContentParametersResponse) SetResult(v CategoryContentParametersDTO) {
	o.Result = &v
}

func (o GetCategoryContentParametersResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCategoryContentParametersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *GetCategoryContentParametersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCategoryContentParametersResponse := _GetCategoryContentParametersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCategoryContentParametersResponse)

	if err != nil {
		return err
	}

	*o = GetCategoryContentParametersResponse(varGetCategoryContentParametersResponse)

	return err
}

type NullableGetCategoryContentParametersResponse struct {
	value *GetCategoryContentParametersResponse
	isSet bool
}

func (v NullableGetCategoryContentParametersResponse) Get() *GetCategoryContentParametersResponse {
	return v.value
}

func (v *NullableGetCategoryContentParametersResponse) Set(val *GetCategoryContentParametersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCategoryContentParametersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCategoryContentParametersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCategoryContentParametersResponse(val *GetCategoryContentParametersResponse) *NullableGetCategoryContentParametersResponse {
	return &NullableGetCategoryContentParametersResponse{value: val, isSet: true}
}

func (v NullableGetCategoryContentParametersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCategoryContentParametersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
