/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetBidsRecommendationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBidsRecommendationsResponse{}

// GetBidsRecommendationsResponse description.
type GetBidsRecommendationsResponse struct {
	Status *ApiResponseStatusType `json:"status,omitempty"`
	Result *GetBidsRecommendationsResponseDTO `json:"result,omitempty"`
}

// NewGetBidsRecommendationsResponse instantiates a new GetBidsRecommendationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBidsRecommendationsResponse() *GetBidsRecommendationsResponse {
	this := GetBidsRecommendationsResponse{}
	return &this
}

// NewGetBidsRecommendationsResponseWithDefaults instantiates a new GetBidsRecommendationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBidsRecommendationsResponseWithDefaults() *GetBidsRecommendationsResponse {
	this := GetBidsRecommendationsResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetBidsRecommendationsResponse) GetStatus() ApiResponseStatusType {
	if o == nil || IsNil(o.Status) {
		var ret ApiResponseStatusType
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBidsRecommendationsResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetBidsRecommendationsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ApiResponseStatusType and assigns it to the Status field.
func (o *GetBidsRecommendationsResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetBidsRecommendationsResponse) GetResult() GetBidsRecommendationsResponseDTO {
	if o == nil || IsNil(o.Result) {
		var ret GetBidsRecommendationsResponseDTO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBidsRecommendationsResponse) GetResultOk() (*GetBidsRecommendationsResponseDTO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetBidsRecommendationsResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GetBidsRecommendationsResponseDTO and assigns it to the Result field.
func (o *GetBidsRecommendationsResponse) SetResult(v GetBidsRecommendationsResponseDTO) {
	o.Result = &v
}

func (o GetBidsRecommendationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBidsRecommendationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableGetBidsRecommendationsResponse struct {
	value *GetBidsRecommendationsResponse
	isSet bool
}

func (v NullableGetBidsRecommendationsResponse) Get() *GetBidsRecommendationsResponse {
	return v.value
}

func (v *NullableGetBidsRecommendationsResponse) Set(val *GetBidsRecommendationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBidsRecommendationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBidsRecommendationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBidsRecommendationsResponse(val *GetBidsRecommendationsResponse) *NullableGetBidsRecommendationsResponse {
	return &NullableGetBidsRecommendationsResponse{value: val, isSet: true}
}

func (v NullableGetBidsRecommendationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBidsRecommendationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


