/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetReportInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReportInfoResponse{}

// GetReportInfoResponse Ответ на запрос информации об отчете или документе.
type GetReportInfoResponse struct {
	Status ApiResponseStatusType `json:"status"`
	Result *ReportInfoDTO        `json:"result,omitempty"`
}

type _GetReportInfoResponse GetReportInfoResponse

// NewGetReportInfoResponse instantiates a new GetReportInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReportInfoResponse(status ApiResponseStatusType) *GetReportInfoResponse {
	this := GetReportInfoResponse{}
	this.Status = status
	return &this
}

// NewGetReportInfoResponseWithDefaults instantiates a new GetReportInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReportInfoResponseWithDefaults() *GetReportInfoResponse {
	this := GetReportInfoResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetReportInfoResponse) GetStatus() ApiResponseStatusType {
	if o == nil {
		var ret ApiResponseStatusType
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetReportInfoResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetReportInfoResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetReportInfoResponse) GetResult() ReportInfoDTO {
	if o == nil || IsNil(o.Result) {
		var ret ReportInfoDTO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReportInfoResponse) GetResultOk() (*ReportInfoDTO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetReportInfoResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ReportInfoDTO and assigns it to the Result field.
func (o *GetReportInfoResponse) SetResult(v ReportInfoDTO) {
	o.Result = &v
}

func (o GetReportInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReportInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *GetReportInfoResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetReportInfoResponse := _GetReportInfoResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetReportInfoResponse)

	if err != nil {
		return err
	}

	*o = GetReportInfoResponse(varGetReportInfoResponse)

	return err
}

type NullableGetReportInfoResponse struct {
	value *GetReportInfoResponse
	isSet bool
}

func (v NullableGetReportInfoResponse) Get() *GetReportInfoResponse {
	return v.value
}

func (v *NullableGetReportInfoResponse) Set(val *GetReportInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReportInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReportInfoResponse) Unset() {
	var zero *GetReportInfoResponse
	v.value = zero
	v.isSet = false
}

func NewNullableGetReportInfoResponse(val *GetReportInfoResponse) *NullableGetReportInfoResponse {
	return &NullableGetReportInfoResponse{value: val, isSet: true}
}

func (v NullableGetReportInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReportInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
