/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ClosureDocumentsContractType Тип договора:  * `INCOME` — договор на размещение.  * `OUTCOME` — договор на продвижение.  * `MARKETING` — договор на маркетинг.
type ClosureDocumentsContractType string

// List of ClosureDocumentsContractType
const (
	CLOSUREDOCUMENTSCONTRACTTYPE_INCOME    ClosureDocumentsContractType = "INCOME"
	CLOSUREDOCUMENTSCONTRACTTYPE_OUTCOME   ClosureDocumentsContractType = "OUTCOME"
	CLOSUREDOCUMENTSCONTRACTTYPE_MARKETING ClosureDocumentsContractType = "MARKETING"
)

// All allowed values of ClosureDocumentsContractType enum
var AllowedClosureDocumentsContractTypeEnumValues = []ClosureDocumentsContractType{
	"INCOME",
	"OUTCOME",
	"MARKETING",
}

func (v *ClosureDocumentsContractType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ClosureDocumentsContractType(value)
	for _, existing := range AllowedClosureDocumentsContractTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ClosureDocumentsContractType", value)
}

// NewClosureDocumentsContractTypeFromValue returns a pointer to a valid ClosureDocumentsContractType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewClosureDocumentsContractTypeFromValue(v string) (*ClosureDocumentsContractType, error) {
	ev := ClosureDocumentsContractType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ClosureDocumentsContractType: valid values are %v", v, AllowedClosureDocumentsContractTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ClosureDocumentsContractType) IsValid() bool {
	for _, existing := range AllowedClosureDocumentsContractTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ClosureDocumentsContractType value
func (v ClosureDocumentsContractType) Ptr() *ClosureDocumentsContractType {
	return &v
}

type NullableClosureDocumentsContractType struct {
	value *ClosureDocumentsContractType
	isSet bool
}

func (v NullableClosureDocumentsContractType) Get() *ClosureDocumentsContractType {
	return v.value
}

func (v *NullableClosureDocumentsContractType) Set(val *ClosureDocumentsContractType) {
	v.value = val
	v.isSet = true
}

func (v NullableClosureDocumentsContractType) IsSet() bool {
	return v.isSet
}

func (v *NullableClosureDocumentsContractType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClosureDocumentsContractType(val *ClosureDocumentsContractType) *NullableClosureDocumentsContractType {
	return &NullableClosureDocumentsContractType{value: val, isSet: true}
}

func (v NullableClosureDocumentsContractType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClosureDocumentsContractType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
