/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeliveryIntervalsUpdateOptionDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryIntervalsUpdateOptionDTO{}

// DeliveryIntervalsUpdateOptionDTO Интервалы дат и времени.
type DeliveryIntervalsUpdateOptionDTO struct {
	DeliveryDateInterval DeliveryDateIntervalDTO `json:"deliveryDateInterval"`
	DeliveryTimeInterval TimeIntervalDTO         `json:"deliveryTimeInterval"`
}

type _DeliveryIntervalsUpdateOptionDTO DeliveryIntervalsUpdateOptionDTO

// NewDeliveryIntervalsUpdateOptionDTO instantiates a new DeliveryIntervalsUpdateOptionDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryIntervalsUpdateOptionDTO(deliveryDateInterval DeliveryDateIntervalDTO, deliveryTimeInterval TimeIntervalDTO) *DeliveryIntervalsUpdateOptionDTO {
	this := DeliveryIntervalsUpdateOptionDTO{}
	this.DeliveryDateInterval = deliveryDateInterval
	this.DeliveryTimeInterval = deliveryTimeInterval
	return &this
}

// NewDeliveryIntervalsUpdateOptionDTOWithDefaults instantiates a new DeliveryIntervalsUpdateOptionDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryIntervalsUpdateOptionDTOWithDefaults() *DeliveryIntervalsUpdateOptionDTO {
	this := DeliveryIntervalsUpdateOptionDTO{}
	return &this
}

// GetDeliveryDateInterval returns the DeliveryDateInterval field value
func (o *DeliveryIntervalsUpdateOptionDTO) GetDeliveryDateInterval() DeliveryDateIntervalDTO {
	if o == nil {
		var ret DeliveryDateIntervalDTO
		return ret
	}

	return o.DeliveryDateInterval
}

// GetDeliveryDateIntervalOk returns a tuple with the DeliveryDateInterval field value
// and a boolean to check if the value has been set.
func (o *DeliveryIntervalsUpdateOptionDTO) GetDeliveryDateIntervalOk() (*DeliveryDateIntervalDTO, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeliveryDateInterval, true
}

// SetDeliveryDateInterval sets field value
func (o *DeliveryIntervalsUpdateOptionDTO) SetDeliveryDateInterval(v DeliveryDateIntervalDTO) {
	o.DeliveryDateInterval = v
}

// GetDeliveryTimeInterval returns the DeliveryTimeInterval field value
func (o *DeliveryIntervalsUpdateOptionDTO) GetDeliveryTimeInterval() TimeIntervalDTO {
	if o == nil {
		var ret TimeIntervalDTO
		return ret
	}

	return o.DeliveryTimeInterval
}

// GetDeliveryTimeIntervalOk returns a tuple with the DeliveryTimeInterval field value
// and a boolean to check if the value has been set.
func (o *DeliveryIntervalsUpdateOptionDTO) GetDeliveryTimeIntervalOk() (*TimeIntervalDTO, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeliveryTimeInterval, true
}

// SetDeliveryTimeInterval sets field value
func (o *DeliveryIntervalsUpdateOptionDTO) SetDeliveryTimeInterval(v TimeIntervalDTO) {
	o.DeliveryTimeInterval = v
}

func (o DeliveryIntervalsUpdateOptionDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryIntervalsUpdateOptionDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deliveryDateInterval"] = o.DeliveryDateInterval
	toSerialize["deliveryTimeInterval"] = o.DeliveryTimeInterval
	return toSerialize, nil
}

func (o *DeliveryIntervalsUpdateOptionDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deliveryDateInterval",
		"deliveryTimeInterval",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliveryIntervalsUpdateOptionDTO := _DeliveryIntervalsUpdateOptionDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliveryIntervalsUpdateOptionDTO)

	if err != nil {
		return err
	}

	*o = DeliveryIntervalsUpdateOptionDTO(varDeliveryIntervalsUpdateOptionDTO)

	return err
}

type NullableDeliveryIntervalsUpdateOptionDTO struct {
	value *DeliveryIntervalsUpdateOptionDTO
	isSet bool
}

func (v NullableDeliveryIntervalsUpdateOptionDTO) Get() *DeliveryIntervalsUpdateOptionDTO {
	return v.value
}

func (v *NullableDeliveryIntervalsUpdateOptionDTO) Set(val *DeliveryIntervalsUpdateOptionDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryIntervalsUpdateOptionDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryIntervalsUpdateOptionDTO) Unset() {
	var zero *DeliveryIntervalsUpdateOptionDTO
	v.value = zero
	v.isSet = false
}

func NewNullableDeliveryIntervalsUpdateOptionDTO(val *DeliveryIntervalsUpdateOptionDTO) *NullableDeliveryIntervalsUpdateOptionDTO {
	return &NullableDeliveryIntervalsUpdateOptionDTO{value: val, isSet: true}
}

func (v NullableDeliveryIntervalsUpdateOptionDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryIntervalsUpdateOptionDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
