/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetReturnDeliveryOptionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReturnDeliveryOptionsResponse{}

// GetReturnDeliveryOptionsResponse Информация о доступных пунктах выдачи.
type GetReturnDeliveryOptionsResponse struct {
	Status ApiResponseStatusType        `json:"status"`
	Result *GetReturnDeliveryOptionsDTO `json:"result,omitempty"`
}

type _GetReturnDeliveryOptionsResponse GetReturnDeliveryOptionsResponse

// NewGetReturnDeliveryOptionsResponse instantiates a new GetReturnDeliveryOptionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReturnDeliveryOptionsResponse(status ApiResponseStatusType) *GetReturnDeliveryOptionsResponse {
	this := GetReturnDeliveryOptionsResponse{}
	this.Status = status
	return &this
}

// NewGetReturnDeliveryOptionsResponseWithDefaults instantiates a new GetReturnDeliveryOptionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReturnDeliveryOptionsResponseWithDefaults() *GetReturnDeliveryOptionsResponse {
	this := GetReturnDeliveryOptionsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetReturnDeliveryOptionsResponse) GetStatus() ApiResponseStatusType {
	if o == nil {
		var ret ApiResponseStatusType
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetReturnDeliveryOptionsResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetReturnDeliveryOptionsResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetReturnDeliveryOptionsResponse) GetResult() GetReturnDeliveryOptionsDTO {
	if o == nil || IsNil(o.Result) {
		var ret GetReturnDeliveryOptionsDTO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReturnDeliveryOptionsResponse) GetResultOk() (*GetReturnDeliveryOptionsDTO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetReturnDeliveryOptionsResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GetReturnDeliveryOptionsDTO and assigns it to the Result field.
func (o *GetReturnDeliveryOptionsResponse) SetResult(v GetReturnDeliveryOptionsDTO) {
	o.Result = &v
}

func (o GetReturnDeliveryOptionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReturnDeliveryOptionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *GetReturnDeliveryOptionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetReturnDeliveryOptionsResponse := _GetReturnDeliveryOptionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetReturnDeliveryOptionsResponse)

	if err != nil {
		return err
	}

	*o = GetReturnDeliveryOptionsResponse(varGetReturnDeliveryOptionsResponse)

	return err
}

type NullableGetReturnDeliveryOptionsResponse struct {
	value *GetReturnDeliveryOptionsResponse
	isSet bool
}

func (v NullableGetReturnDeliveryOptionsResponse) Get() *GetReturnDeliveryOptionsResponse {
	return v.value
}

func (v *NullableGetReturnDeliveryOptionsResponse) Set(val *GetReturnDeliveryOptionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReturnDeliveryOptionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReturnDeliveryOptionsResponse) Unset() {
	var zero *GetReturnDeliveryOptionsResponse
	v.value = zero
	v.isSet = false
}

func NewNullableGetReturnDeliveryOptionsResponse(val *GetReturnDeliveryOptionsResponse) *NullableGetReturnDeliveryOptionsResponse {
	return &NullableGetReturnDeliveryOptionsResponse{value: val, isSet: true}
}

func (v NullableGetReturnDeliveryOptionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReturnDeliveryOptionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
