/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetReturnsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReturnsResponse{}

// GetReturnsResponse struct for GetReturnsResponse
type GetReturnsResponse struct {
	Status *ApiResponseStatusType `json:"status,omitempty"`
	Result *PagedReturnsDTO       `json:"result,omitempty"`
}

// NewGetReturnsResponse instantiates a new GetReturnsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReturnsResponse() *GetReturnsResponse {
	this := GetReturnsResponse{}
	return &this
}

// NewGetReturnsResponseWithDefaults instantiates a new GetReturnsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReturnsResponseWithDefaults() *GetReturnsResponse {
	this := GetReturnsResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetReturnsResponse) GetStatus() ApiResponseStatusType {
	if o == nil || IsNil(o.Status) {
		var ret ApiResponseStatusType
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReturnsResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetReturnsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ApiResponseStatusType and assigns it to the Status field.
func (o *GetReturnsResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetReturnsResponse) GetResult() PagedReturnsDTO {
	if o == nil || IsNil(o.Result) {
		var ret PagedReturnsDTO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReturnsResponse) GetResultOk() (*PagedReturnsDTO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetReturnsResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given PagedReturnsDTO and assigns it to the Result field.
func (o *GetReturnsResponse) SetResult(v PagedReturnsDTO) {
	o.Result = &v
}

func (o GetReturnsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReturnsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableGetReturnsResponse struct {
	value *GetReturnsResponse
	isSet bool
}

func (v NullableGetReturnsResponse) Get() *GetReturnsResponse {
	return v.value
}

func (v *NullableGetReturnsResponse) Set(val *GetReturnsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReturnsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReturnsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReturnsResponse(val *GetReturnsResponse) *NullableGetReturnsResponse {
	return &NullableGetReturnsResponse{value: val, isSet: true}
}

func (v NullableGetReturnsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReturnsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
