/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreatedReturnDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatedReturnDTO{}

// CreatedReturnDTO Информация о созданном возврате.
type CreatedReturnDTO struct {
	// Идентификатор возврата.
	Id int64 `json:"id"`
}

type _CreatedReturnDTO CreatedReturnDTO

// NewCreatedReturnDTO instantiates a new CreatedReturnDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedReturnDTO(id int64) *CreatedReturnDTO {
	this := CreatedReturnDTO{}
	this.Id = id
	return &this
}

// NewCreatedReturnDTOWithDefaults instantiates a new CreatedReturnDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedReturnDTOWithDefaults() *CreatedReturnDTO {
	this := CreatedReturnDTO{}
	return &this
}

// GetId returns the Id field value
func (o *CreatedReturnDTO) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreatedReturnDTO) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreatedReturnDTO) SetId(v int64) {
	o.Id = v
}

func (o CreatedReturnDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatedReturnDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CreatedReturnDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatedReturnDTO := _CreatedReturnDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatedReturnDTO)

	if err != nil {
		return err
	}

	*o = CreatedReturnDTO(varCreatedReturnDTO)

	return err
}

type NullableCreatedReturnDTO struct {
	value *CreatedReturnDTO
	isSet bool
}

func (v NullableCreatedReturnDTO) Get() *CreatedReturnDTO {
	return v.value
}

func (v *NullableCreatedReturnDTO) Set(val *CreatedReturnDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedReturnDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedReturnDTO) Unset() {
	var zero *CreatedReturnDTO
	v.value = zero
	v.isSet = false
}

func NewNullableCreatedReturnDTO(val *CreatedReturnDTO) *NullableCreatedReturnDTO {
	return &NullableCreatedReturnDTO{value: val, isSet: true}
}

func (v NullableCreatedReturnDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedReturnDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
