/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ParcelRequestDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParcelRequestDTO{}

// ParcelRequestDTO Информация о грузовых местах в заказе.
type ParcelRequestDTO struct {
	// Список грузовых мест. По его длине Маркет определяет количество мест.
	Boxes []ParcelBoxRequestDTO `json:"boxes"`
}

type _ParcelRequestDTO ParcelRequestDTO

// NewParcelRequestDTO instantiates a new ParcelRequestDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParcelRequestDTO(boxes []ParcelBoxRequestDTO) *ParcelRequestDTO {
	this := ParcelRequestDTO{}
	this.Boxes = boxes
	return &this
}

// NewParcelRequestDTOWithDefaults instantiates a new ParcelRequestDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParcelRequestDTOWithDefaults() *ParcelRequestDTO {
	this := ParcelRequestDTO{}
	return &this
}

// GetBoxes returns the Boxes field value
func (o *ParcelRequestDTO) GetBoxes() []ParcelBoxRequestDTO {
	if o == nil {
		var ret []ParcelBoxRequestDTO
		return ret
	}

	return o.Boxes
}

// GetBoxesOk returns a tuple with the Boxes field value
// and a boolean to check if the value has been set.
func (o *ParcelRequestDTO) GetBoxesOk() ([]ParcelBoxRequestDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.Boxes, true
}

// SetBoxes sets field value
func (o *ParcelRequestDTO) SetBoxes(v []ParcelBoxRequestDTO) {
	o.Boxes = v
}

func (o ParcelRequestDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParcelRequestDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["boxes"] = o.Boxes
	return toSerialize, nil
}

func (o *ParcelRequestDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"boxes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParcelRequestDTO := _ParcelRequestDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varParcelRequestDTO)

	if err != nil {
		return err
	}

	*o = ParcelRequestDTO(varParcelRequestDTO)

	return err
}

type NullableParcelRequestDTO struct {
	value *ParcelRequestDTO
	isSet bool
}

func (v NullableParcelRequestDTO) Get() *ParcelRequestDTO {
	return v.value
}

func (v *NullableParcelRequestDTO) Set(val *ParcelRequestDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableParcelRequestDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableParcelRequestDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParcelRequestDTO(val *ParcelRequestDTO) *NullableParcelRequestDTO {
	return &NullableParcelRequestDTO{value: val, isSet: true}
}

func (v NullableParcelRequestDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParcelRequestDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
