/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateGoodsQuestionTextEntityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGoodsQuestionTextEntityRequest{}

// UpdateGoodsQuestionTextEntityRequest Запрос на создание, обновление или удаление вопроса, ответа или комментария.  **Параметры для разных операций:**  * `CREATE` — создание ответа или комментария:   * Обязательно: `operationType`, `parentEntityId`, `text`.   * `parentEntityId` — идентификатор родителя (для ответа — вопроса, для комментария — ответа).  * `UPDATE` — обновление ответа или комментария:   * Обязательно: `operationType`, `entityId`, `text`.   * `entityId` — идентификатор ответа или комментария.  * `DELETE` — удаление ответа или комментария:   * Обязательно: `operationType`, `entityId`.   * `text` не требуется.
type UpdateGoodsQuestionTextEntityRequest struct {
	EntityId       *TypedQuestionsTextEntityIdDTO `json:"entityId,omitempty"`
	ParentEntityId *TypedQuestionsTextEntityIdDTO `json:"parentEntityId,omitempty"`
	// Текстовое содержимое.
	Text          *string                          `json:"text,omitempty"`
	OperationType QuestionsTextEntityOperationType `json:"operationType"`
}

type _UpdateGoodsQuestionTextEntityRequest UpdateGoodsQuestionTextEntityRequest

// NewUpdateGoodsQuestionTextEntityRequest instantiates a new UpdateGoodsQuestionTextEntityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGoodsQuestionTextEntityRequest(operationType QuestionsTextEntityOperationType) *UpdateGoodsQuestionTextEntityRequest {
	this := UpdateGoodsQuestionTextEntityRequest{}
	this.OperationType = operationType
	return &this
}

// NewUpdateGoodsQuestionTextEntityRequestWithDefaults instantiates a new UpdateGoodsQuestionTextEntityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGoodsQuestionTextEntityRequestWithDefaults() *UpdateGoodsQuestionTextEntityRequest {
	this := UpdateGoodsQuestionTextEntityRequest{}
	return &this
}

// GetEntityId returns the EntityId field value if set, zero value otherwise.
func (o *UpdateGoodsQuestionTextEntityRequest) GetEntityId() TypedQuestionsTextEntityIdDTO {
	if o == nil || IsNil(o.EntityId) {
		var ret TypedQuestionsTextEntityIdDTO
		return ret
	}
	return *o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGoodsQuestionTextEntityRequest) GetEntityIdOk() (*TypedQuestionsTextEntityIdDTO, bool) {
	if o == nil || IsNil(o.EntityId) {
		return nil, false
	}
	return o.EntityId, true
}

// HasEntityId returns a boolean if a field has been set.
func (o *UpdateGoodsQuestionTextEntityRequest) HasEntityId() bool {
	if o != nil && !IsNil(o.EntityId) {
		return true
	}

	return false
}

// SetEntityId gets a reference to the given TypedQuestionsTextEntityIdDTO and assigns it to the EntityId field.
func (o *UpdateGoodsQuestionTextEntityRequest) SetEntityId(v TypedQuestionsTextEntityIdDTO) {
	o.EntityId = &v
}

// GetParentEntityId returns the ParentEntityId field value if set, zero value otherwise.
func (o *UpdateGoodsQuestionTextEntityRequest) GetParentEntityId() TypedQuestionsTextEntityIdDTO {
	if o == nil || IsNil(o.ParentEntityId) {
		var ret TypedQuestionsTextEntityIdDTO
		return ret
	}
	return *o.ParentEntityId
}

// GetParentEntityIdOk returns a tuple with the ParentEntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGoodsQuestionTextEntityRequest) GetParentEntityIdOk() (*TypedQuestionsTextEntityIdDTO, bool) {
	if o == nil || IsNil(o.ParentEntityId) {
		return nil, false
	}
	return o.ParentEntityId, true
}

// HasParentEntityId returns a boolean if a field has been set.
func (o *UpdateGoodsQuestionTextEntityRequest) HasParentEntityId() bool {
	if o != nil && !IsNil(o.ParentEntityId) {
		return true
	}

	return false
}

// SetParentEntityId gets a reference to the given TypedQuestionsTextEntityIdDTO and assigns it to the ParentEntityId field.
func (o *UpdateGoodsQuestionTextEntityRequest) SetParentEntityId(v TypedQuestionsTextEntityIdDTO) {
	o.ParentEntityId = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *UpdateGoodsQuestionTextEntityRequest) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGoodsQuestionTextEntityRequest) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *UpdateGoodsQuestionTextEntityRequest) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *UpdateGoodsQuestionTextEntityRequest) SetText(v string) {
	o.Text = &v
}

// GetOperationType returns the OperationType field value
func (o *UpdateGoodsQuestionTextEntityRequest) GetOperationType() QuestionsTextEntityOperationType {
	if o == nil {
		var ret QuestionsTextEntityOperationType
		return ret
	}

	return o.OperationType
}

// GetOperationTypeOk returns a tuple with the OperationType field value
// and a boolean to check if the value has been set.
func (o *UpdateGoodsQuestionTextEntityRequest) GetOperationTypeOk() (*QuestionsTextEntityOperationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationType, true
}

// SetOperationType sets field value
func (o *UpdateGoodsQuestionTextEntityRequest) SetOperationType(v QuestionsTextEntityOperationType) {
	o.OperationType = v
}

func (o UpdateGoodsQuestionTextEntityRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGoodsQuestionTextEntityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EntityId) {
		toSerialize["entityId"] = o.EntityId
	}
	if !IsNil(o.ParentEntityId) {
		toSerialize["parentEntityId"] = o.ParentEntityId
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	toSerialize["operationType"] = o.OperationType
	return toSerialize, nil
}

func (o *UpdateGoodsQuestionTextEntityRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operationType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGoodsQuestionTextEntityRequest := _UpdateGoodsQuestionTextEntityRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGoodsQuestionTextEntityRequest)

	if err != nil {
		return err
	}

	*o = UpdateGoodsQuestionTextEntityRequest(varUpdateGoodsQuestionTextEntityRequest)

	return err
}

type NullableUpdateGoodsQuestionTextEntityRequest struct {
	value *UpdateGoodsQuestionTextEntityRequest
	isSet bool
}

func (v NullableUpdateGoodsQuestionTextEntityRequest) Get() *UpdateGoodsQuestionTextEntityRequest {
	return v.value
}

func (v *NullableUpdateGoodsQuestionTextEntityRequest) Set(val *UpdateGoodsQuestionTextEntityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGoodsQuestionTextEntityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGoodsQuestionTextEntityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGoodsQuestionTextEntityRequest(val *UpdateGoodsQuestionTextEntityRequest) *NullableUpdateGoodsQuestionTextEntityRequest {
	return &NullableUpdateGoodsQuestionTextEntityRequest{value: val, isSet: true}
}

func (v NullableUpdateGoodsQuestionTextEntityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGoodsQuestionTextEntityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
