/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseCampaignOfferDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseCampaignOfferDTO{}

// BaseCampaignOfferDTO Информация о новой цене на товар.
type BaseCampaignOfferDTO struct {
	// Ваш SKU — идентификатор товара в вашей системе.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  SKU товара можно изменить в кабинете продавца на Маркете. О том, как это сделать, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/assortment/operations/edit-sku).  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields) 
	OfferId string `json:"offerId" validate:"regexp=^(?=.*\\\\S.*)[^\\\\x00-\\\\x08\\\\x0A-\\\\x1f\\\\x7f]{1,255}$"`
	Quantum *QuantumDTO `json:"quantum,omitempty"`
	// {% note warning \"Вместо него используйте методы скрытия товаров с витрины\" %}  * [GET campaigns/{campaignId}/hidden-offers](../../reference/assortment/getHiddenOffers.md) — просмотр скрытых товаров; * [POST campaigns/{campaignId}/hidden-offers](../../reference/assortment/addHiddenOffers.md) — скрытие товаров; * [POST campaigns/{campaignId}/hidden-offers/delete](../../reference/assortment/deleteHiddenOffers.md) — возобновление показа.  {% endnote %}  Есть ли товар в продаже. 
	// Deprecated
	Available *bool `json:"available,omitempty"`
}

type _BaseCampaignOfferDTO BaseCampaignOfferDTO

// NewBaseCampaignOfferDTO instantiates a new BaseCampaignOfferDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseCampaignOfferDTO(offerId string) *BaseCampaignOfferDTO {
	this := BaseCampaignOfferDTO{}
	this.OfferId = offerId
	return &this
}

// NewBaseCampaignOfferDTOWithDefaults instantiates a new BaseCampaignOfferDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseCampaignOfferDTOWithDefaults() *BaseCampaignOfferDTO {
	this := BaseCampaignOfferDTO{}
	return &this
}

// GetOfferId returns the OfferId field value
func (o *BaseCampaignOfferDTO) GetOfferId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfferId
}

// GetOfferIdOk returns a tuple with the OfferId field value
// and a boolean to check if the value has been set.
func (o *BaseCampaignOfferDTO) GetOfferIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfferId, true
}

// SetOfferId sets field value
func (o *BaseCampaignOfferDTO) SetOfferId(v string) {
	o.OfferId = v
}

// GetQuantum returns the Quantum field value if set, zero value otherwise.
func (o *BaseCampaignOfferDTO) GetQuantum() QuantumDTO {
	if o == nil || IsNil(o.Quantum) {
		var ret QuantumDTO
		return ret
	}
	return *o.Quantum
}

// GetQuantumOk returns a tuple with the Quantum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseCampaignOfferDTO) GetQuantumOk() (*QuantumDTO, bool) {
	if o == nil || IsNil(o.Quantum) {
		return nil, false
	}
	return o.Quantum, true
}

// HasQuantum returns a boolean if a field has been set.
func (o *BaseCampaignOfferDTO) HasQuantum() bool {
	if o != nil && !IsNil(o.Quantum) {
		return true
	}

	return false
}

// SetQuantum gets a reference to the given QuantumDTO and assigns it to the Quantum field.
func (o *BaseCampaignOfferDTO) SetQuantum(v QuantumDTO) {
	o.Quantum = &v
}

// GetAvailable returns the Available field value if set, zero value otherwise.
// Deprecated
func (o *BaseCampaignOfferDTO) GetAvailable() bool {
	if o == nil || IsNil(o.Available) {
		var ret bool
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *BaseCampaignOfferDTO) GetAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *BaseCampaignOfferDTO) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given bool and assigns it to the Available field.
// Deprecated
func (o *BaseCampaignOfferDTO) SetAvailable(v bool) {
	o.Available = &v
}

func (o BaseCampaignOfferDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseCampaignOfferDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["offerId"] = o.OfferId
	if !IsNil(o.Quantum) {
		toSerialize["quantum"] = o.Quantum
	}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	return toSerialize, nil
}

func (o *BaseCampaignOfferDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"offerId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseCampaignOfferDTO := _BaseCampaignOfferDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseCampaignOfferDTO)

	if err != nil {
		return err
	}

	*o = BaseCampaignOfferDTO(varBaseCampaignOfferDTO)

	return err
}

type NullableBaseCampaignOfferDTO struct {
	value *BaseCampaignOfferDTO
	isSet bool
}

func (v NullableBaseCampaignOfferDTO) Get() *BaseCampaignOfferDTO {
	return v.value
}

func (v *NullableBaseCampaignOfferDTO) Set(val *BaseCampaignOfferDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseCampaignOfferDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseCampaignOfferDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseCampaignOfferDTO(val *BaseCampaignOfferDTO) *NullableBaseCampaignOfferDTO {
	return &NullableBaseCampaignOfferDTO{value: val, isSet: true}
}

func (v NullableBaseCampaignOfferDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseCampaignOfferDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


