/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateWarehouseStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateWarehouseStatusResponse{}

// UpdateWarehouseStatusResponse struct for UpdateWarehouseStatusResponse
type UpdateWarehouseStatusResponse struct {
	Status ApiResponseStatusType `json:"status"`
	Result *WarehouseStatusDTO   `json:"result,omitempty"`
}

type _UpdateWarehouseStatusResponse UpdateWarehouseStatusResponse

// NewUpdateWarehouseStatusResponse instantiates a new UpdateWarehouseStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateWarehouseStatusResponse(status ApiResponseStatusType) *UpdateWarehouseStatusResponse {
	this := UpdateWarehouseStatusResponse{}
	this.Status = status
	return &this
}

// NewUpdateWarehouseStatusResponseWithDefaults instantiates a new UpdateWarehouseStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateWarehouseStatusResponseWithDefaults() *UpdateWarehouseStatusResponse {
	this := UpdateWarehouseStatusResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateWarehouseStatusResponse) GetStatus() ApiResponseStatusType {
	if o == nil {
		var ret ApiResponseStatusType
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateWarehouseStatusResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateWarehouseStatusResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *UpdateWarehouseStatusResponse) GetResult() WarehouseStatusDTO {
	if o == nil || IsNil(o.Result) {
		var ret WarehouseStatusDTO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateWarehouseStatusResponse) GetResultOk() (*WarehouseStatusDTO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *UpdateWarehouseStatusResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given WarehouseStatusDTO and assigns it to the Result field.
func (o *UpdateWarehouseStatusResponse) SetResult(v WarehouseStatusDTO) {
	o.Result = &v
}

func (o UpdateWarehouseStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateWarehouseStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *UpdateWarehouseStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateWarehouseStatusResponse := _UpdateWarehouseStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateWarehouseStatusResponse)

	if err != nil {
		return err
	}

	*o = UpdateWarehouseStatusResponse(varUpdateWarehouseStatusResponse)

	return err
}

type NullableUpdateWarehouseStatusResponse struct {
	value *UpdateWarehouseStatusResponse
	isSet bool
}

func (v NullableUpdateWarehouseStatusResponse) Get() *UpdateWarehouseStatusResponse {
	return v.value
}

func (v *NullableUpdateWarehouseStatusResponse) Set(val *UpdateWarehouseStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateWarehouseStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateWarehouseStatusResponse) Unset() {
	var zero *UpdateWarehouseStatusResponse
	v.value = zero
	v.isSet = false
}

func NewNullableUpdateWarehouseStatusResponse(val *UpdateWarehouseStatusResponse) *NullableUpdateWarehouseStatusResponse {
	return &NullableUpdateWarehouseStatusResponse{value: val, isSet: true}
}

func (v NullableUpdateWarehouseStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateWarehouseStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
