/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetPromoOffersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPromoOffersResponse{}

// GetPromoOffersResponse struct for GetPromoOffersResponse
type GetPromoOffersResponse struct {
	Status ApiResponseStatusType    `json:"status"`
	Result *GetPromoOffersResultDTO `json:"result,omitempty"`
}

type _GetPromoOffersResponse GetPromoOffersResponse

// NewGetPromoOffersResponse instantiates a new GetPromoOffersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPromoOffersResponse(status ApiResponseStatusType) *GetPromoOffersResponse {
	this := GetPromoOffersResponse{}
	this.Status = status
	return &this
}

// NewGetPromoOffersResponseWithDefaults instantiates a new GetPromoOffersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPromoOffersResponseWithDefaults() *GetPromoOffersResponse {
	this := GetPromoOffersResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetPromoOffersResponse) GetStatus() ApiResponseStatusType {
	if o == nil {
		var ret ApiResponseStatusType
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetPromoOffersResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetPromoOffersResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetPromoOffersResponse) GetResult() GetPromoOffersResultDTO {
	if o == nil || IsNil(o.Result) {
		var ret GetPromoOffersResultDTO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPromoOffersResponse) GetResultOk() (*GetPromoOffersResultDTO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetPromoOffersResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GetPromoOffersResultDTO and assigns it to the Result field.
func (o *GetPromoOffersResponse) SetResult(v GetPromoOffersResultDTO) {
	o.Result = &v
}

func (o GetPromoOffersResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPromoOffersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *GetPromoOffersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPromoOffersResponse := _GetPromoOffersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPromoOffersResponse)

	if err != nil {
		return err
	}

	*o = GetPromoOffersResponse(varGetPromoOffersResponse)

	return err
}

type NullableGetPromoOffersResponse struct {
	value *GetPromoOffersResponse
	isSet bool
}

func (v NullableGetPromoOffersResponse) Get() *GetPromoOffersResponse {
	return v.value
}

func (v *NullableGetPromoOffersResponse) Set(val *GetPromoOffersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPromoOffersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPromoOffersResponse) Unset() {
	var zero *GetPromoOffersResponse
	v.value = zero
	v.isSet = false
}

func NewNullableGetPromoOffersResponse(val *GetPromoOffersResponse) *NullableGetPromoOffersResponse {
	return &NullableGetPromoOffersResponse{value: val, isSet: true}
}

func (v NullableGetPromoOffersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPromoOffersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
