/*
Партнерский API Маркета

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetChatMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetChatMessageResponse{}

// GetChatMessageResponse struct for GetChatMessageResponse
type GetChatMessageResponse struct {
	Status *ApiResponseStatusType `json:"status,omitempty"`
	Result *ChatMessageDTO `json:"result,omitempty"`
}

// NewGetChatMessageResponse instantiates a new GetChatMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChatMessageResponse() *GetChatMessageResponse {
	this := GetChatMessageResponse{}
	return &this
}

// NewGetChatMessageResponseWithDefaults instantiates a new GetChatMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChatMessageResponseWithDefaults() *GetChatMessageResponse {
	this := GetChatMessageResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetChatMessageResponse) GetStatus() ApiResponseStatusType {
	if o == nil || IsNil(o.Status) {
		var ret ApiResponseStatusType
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChatMessageResponse) GetStatusOk() (*ApiResponseStatusType, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetChatMessageResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ApiResponseStatusType and assigns it to the Status field.
func (o *GetChatMessageResponse) SetStatus(v ApiResponseStatusType) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GetChatMessageResponse) GetResult() ChatMessageDTO {
	if o == nil || IsNil(o.Result) {
		var ret ChatMessageDTO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChatMessageResponse) GetResultOk() (*ChatMessageDTO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GetChatMessageResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ChatMessageDTO and assigns it to the Result field.
func (o *GetChatMessageResponse) SetResult(v ChatMessageDTO) {
	o.Result = &v
}

func (o GetChatMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetChatMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableGetChatMessageResponse struct {
	value *GetChatMessageResponse
	isSet bool
}

func (v NullableGetChatMessageResponse) Get() *GetChatMessageResponse {
	return v.value
}

func (v *NullableGetChatMessageResponse) Set(val *GetChatMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChatMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChatMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChatMessageResponse(val *GetChatMessageResponse) *NullableGetChatMessageResponse {
	return &NullableGetChatMessageResponse{value: val, isSet: true}
}

func (v NullableGetChatMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChatMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


