/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CancelReturnRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelReturnRequest{}

// CancelReturnRequest struct for CancelReturnRequest
type CancelReturnRequest struct {
	// Идентификатор возврата.
	ReturnId int64 `json:"returnId"`
}

type _CancelReturnRequest CancelReturnRequest

// NewCancelReturnRequest instantiates a new CancelReturnRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelReturnRequest(returnId int64) *CancelReturnRequest {
	this := CancelReturnRequest{}
	this.ReturnId = returnId
	return &this
}

// NewCancelReturnRequestWithDefaults instantiates a new CancelReturnRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelReturnRequestWithDefaults() *CancelReturnRequest {
	this := CancelReturnRequest{}
	return &this
}

// GetReturnId returns the ReturnId field value
func (o *CancelReturnRequest) GetReturnId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ReturnId
}

// GetReturnIdOk returns a tuple with the ReturnId field value
// and a boolean to check if the value has been set.
func (o *CancelReturnRequest) GetReturnIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnId, true
}

// SetReturnId sets field value
func (o *CancelReturnRequest) SetReturnId(v int64) {
	o.ReturnId = v
}

func (o CancelReturnRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelReturnRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["returnId"] = o.ReturnId
	return toSerialize, nil
}

func (o *CancelReturnRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"returnId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelReturnRequest := _CancelReturnRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelReturnRequest)

	if err != nil {
		return err
	}

	*o = CancelReturnRequest(varCancelReturnRequest)

	return err
}

type NullableCancelReturnRequest struct {
	value *CancelReturnRequest
	isSet bool
}

func (v NullableCancelReturnRequest) Get() *CancelReturnRequest {
	return v.value
}

func (v *NullableCancelReturnRequest) Set(val *CancelReturnRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelReturnRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelReturnRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelReturnRequest(val *CancelReturnRequest) *NullableCancelReturnRequest {
	return &NullableCancelReturnRequest{value: val, isSet: true}
}

func (v NullableCancelReturnRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelReturnRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
