/*
API Яндекс Маркета для продавцов

API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.

API version: LATEST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OrderItemUnitStatusType Статус единицы товара в заказе.  * `CREATED` — создана.  * `SHIPPED` — передана в доставку.  * `CANCELLED` — отменена или удалена из заказа.  * `DELIVERED_TO_BUYER` — передана покупателю.  * `LOST` — утеряна.  * `REJECTED` — невыкупленная.  * `RETURNED` — возвращенная.
type OrderItemUnitStatusType string

// List of OrderItemUnitStatusType
const (
	ORDERITEMUNITSTATUSTYPE_CREATED            OrderItemUnitStatusType = "CREATED"
	ORDERITEMUNITSTATUSTYPE_SHIPPED            OrderItemUnitStatusType = "SHIPPED"
	ORDERITEMUNITSTATUSTYPE_CANCELLED          OrderItemUnitStatusType = "CANCELLED"
	ORDERITEMUNITSTATUSTYPE_DELIVERED_TO_BUYER OrderItemUnitStatusType = "DELIVERED_TO_BUYER"
	ORDERITEMUNITSTATUSTYPE_LOST               OrderItemUnitStatusType = "LOST"
	ORDERITEMUNITSTATUSTYPE_REJECTED           OrderItemUnitStatusType = "REJECTED"
	ORDERITEMUNITSTATUSTYPE_RETURNED           OrderItemUnitStatusType = "RETURNED"
)

// All allowed values of OrderItemUnitStatusType enum
var AllowedOrderItemUnitStatusTypeEnumValues = []OrderItemUnitStatusType{
	"CREATED",
	"SHIPPED",
	"CANCELLED",
	"DELIVERED_TO_BUYER",
	"LOST",
	"REJECTED",
	"RETURNED",
}

func (v *OrderItemUnitStatusType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrderItemUnitStatusType(value)
	for _, existing := range AllowedOrderItemUnitStatusTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrderItemUnitStatusType", value)
}

// NewOrderItemUnitStatusTypeFromValue returns a pointer to a valid OrderItemUnitStatusType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOrderItemUnitStatusTypeFromValue(v string) (*OrderItemUnitStatusType, error) {
	ev := OrderItemUnitStatusType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OrderItemUnitStatusType: valid values are %v", v, AllowedOrderItemUnitStatusTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OrderItemUnitStatusType) IsValid() bool {
	for _, existing := range AllowedOrderItemUnitStatusTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OrderItemUnitStatusType value
func (v OrderItemUnitStatusType) Ptr() *OrderItemUnitStatusType {
	return &v
}

type NullableOrderItemUnitStatusType struct {
	value *OrderItemUnitStatusType
	isSet bool
}

func (v NullableOrderItemUnitStatusType) Get() *OrderItemUnitStatusType {
	return v.value
}

func (v *NullableOrderItemUnitStatusType) Set(val *OrderItemUnitStatusType) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderItemUnitStatusType) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderItemUnitStatusType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderItemUnitStatusType(val *OrderItemUnitStatusType) *NullableOrderItemUnitStatusType {
	return &NullableOrderItemUnitStatusType{value: val, isSet: true}
}

func (v NullableOrderItemUnitStatusType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderItemUnitStatusType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
